import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "./context/AuthProvider";
import NavBar from "./components/NavBar";
import ManualSyncButton from "../components/ui/ManualSyncButton"; //FLUKEGAS ADDED


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <NavBar /> 
          {/* ปุ่ม Manual Sync ชิดขวา */} 
          <div style={{ padding: "12px 16px", display: "flex", justifyContent: "flex-end" }}> 
           <ManualSyncButton />
          </div>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
